"""
Exports two JSON files for the static dashboard artifact (which can't run a
live Python backend once published): 
  1. villages_scored.json   -- every village fully scored by the REAL model
  2. simulation_bagula.json -- an 8-week worsening trajectory for one village,
     generated by calling the real what-if scorer at each stage (not hand-typed).
"""
import sys, os, json
sys.path.insert(0, os.path.dirname(__file__))
from app import main, engine

OUT = os.path.join(os.path.dirname(__file__), "..", "frontend_data")
os.makedirs(OUT, exist_ok=True)

# 1. All villages, fully scored
villages = main.list_villages()
full = [main.village_detail(v["village"]) for v in villages]
with open(os.path.join(OUT, "villages_scored.json"), "w") as f:
    json.dump(full, f, indent=2, default=str)

# 2. Real 8-week simulated trajectory for Bagula, using the actual model
#    (not authored numbers) — a realistic worsening rainfall-deficit + crop
#    stress + market + employment shock, staged week by week.
stages = [
    {"week": 0, "note": "Baseline — normal monsoon pattern.",
     "overrides": {"rainfall_anomaly_pct": -3, "crop_stress_index": 5,
                   "mandi_price_deviation_pct": 1, "mgnrega_demand_spike_pct": 2,
                   "water_stress_index": 8}},
    {"week": 2, "note": "Rainfall anomaly first detected; crop stress not yet visible.",
     "overrides": {"rainfall_anomaly_pct": -16, "crop_stress_index": 14,
                   "mandi_price_deviation_pct": -2, "mgnrega_demand_spike_pct": 4,
                   "water_stress_index": 18}},
    {"week": 4, "note": "Crop stress confirmed; mandi arrivals softening.",
     "overrides": {"rainfall_anomaly_pct": -28, "crop_stress_index": 38,
                   "mandi_price_deviation_pct": -11, "mgnrega_demand_spike_pct": 9,
                   "water_stress_index": 32}},
    {"week": 6, "note": "MGNREGA demand spike registered — income-loss cascade underway.",
     "overrides": {"rainfall_anomaly_pct": -34, "crop_stress_index": 55,
                   "mandi_price_deviation_pct": -19, "mgnrega_demand_spike_pct": 22,
                   "water_stress_index": 41}},
    {"week": 8, "note": "Distress-migration pressure rising.",
     "overrides": {"rainfall_anomaly_pct": -37, "crop_stress_index": 63,
                   "mandi_price_deviation_pct": -24, "mgnrega_demand_spike_pct": 31,
                   "water_stress_index": 47}},
]

village_row = None
import pandas as pd
df = main.load_snapshot()
base = df[df["village"] == "Bagula"].iloc[0]

sim = []
first_watch_week = None
first_critical_week = None
for s in stages:
    row = base.copy()
    for k, v in s["overrides"].items():
        row[k] = v
    result = engine.score_village(row[engine.FEATURES].to_dict())
    interventions = engine.rank_interventions(row[engine.FEATURES].to_dict(), result)
    if first_watch_week is None and result["status"] in ("watch", "risk", "critical"):
        first_watch_week = s["week"]
    if first_critical_week is None and result["status"] == "critical":
        first_critical_week = s["week"]
    sim.append({
        "week": s["week"], "note": s["note"],
        "risk_score": result["risk_score"], "status": result["status"],
        "drivers": result["drivers"], "cascade": result["cascade"],
        "interventions": interventions,
    })

lead_time_weeks = (
    (first_critical_week - first_watch_week)
    if (first_watch_week is not None and first_critical_week is not None)
    else None
)
with open(os.path.join(OUT, "simulation_bagula.json"), "w") as f:
    json.dump({"village": "Bagula", "stages": sim, "first_watch_week": first_watch_week,
               "first_critical_week": first_critical_week, "lead_time_weeks": lead_time_weeks}, f, indent=2)

print("Exported", len(full), "villages.")
print("Simulation lead time (weeks of warning before critical):", lead_time_weeks)
for s in sim:
    print(f"  week {s['week']:>2}  score={s['risk_score']:>3}  status={s['status']:<8}  {s['note']}")
